# Generated by Django 2.1 on 2018-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('display_name', models.CharField(max_length=255)),
                ('display_address', models.CharField(max_length=511)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
